directories:
  output: release
  buildResources: resources
appId: com.nodeweaver.app
productName: NodeWeaver
copyright: Copyright Â© 2024 NodeWeaver
files:
  - filter:
      - dist/**/*
      - renderer/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
mac:
  target:
    - dmg
    - zip
  category: public.app-category.developer-tools
linux:
  target:
    - AppImage
    - deb
  category: Development
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 28.1.0
